### ISSUE TITLE
Faire le Css de la page

### ISSUE THREAD

**Issue by MassylBoul** [MassylBoul/MassylBoul#6]
Créer un fichier Css et le lier à la page détailProjet

**Comment by MassylBoul** [comment]
le fichier css s'appelle detailProjet.css et ce trouve dans le répertoire des css.
Il sert pour l'instant uniquement pour la page detailProjet.html

**Comment by MassylBoul** [comment]
le css et fait mais il reste à le mettre au propre

**Comment by adryserage** [comment]
Voici quelques améliorations à tester de ton côté et à me dire `si c'est une bonne idée :) avec un screenshot avant et après.`

### 1. **Amélioration du responsive design**
Actuellement, la mise en page passe en colonne sur les écrans inférieurs à 991px, mais tu peux améliorer la gestion des tailles intermédiaires pour un meilleur rendu en ajustant la largeur et la disposition :

```css
@media (max-width: 1200px) {
  .main-title {
    font-size: 2.2em; /* Réduire légèrement la taille du titre */
  }

  .section-title {
    font-size: 1.15em;
  }

  .description-text {
    font-size: 1em;
  }
}

@media (max-width: 768px) {
  .wrapper {
    padding: 50px 15px; /* Réduire le padding pour éviter un effet trop aéré */
  }

  .main-title {
    font-size: 2em;
    text-align: center;
  }

  .text-section {
    align-items: center;
    text-align: center;
  }

  .image-section {
    justify-content: center;
  }

  .image-item {
    max-width: 90%;
  }
}
```

---

### 2. **Ajout d'un effet de hover sur l'image**
Ajoute un effet au passage de la souris sur l'image pour une touche d'interactivité :

```css
.image-item {
  transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
}

.image-item:hover {
  transform: scale(1.05); /* Zoom léger */
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.15);
}
```

---

### 3. **Effet subtil sur la carte**
Ajoute une transition douce à `.card-section` pour améliorer l'expérience utilisateur :

```css
.card-section {
  transition: box-shadow 0.3s ease-in-out;
}

.card-section:hover {
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);
}
```

---

### 4. **Ajout d'une animation à l'apparition des éléments**
Pour un effet fluide au chargement de la page :

```css
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.wrapper {
  animation: fadeInUp 0.8s ease-in-out;
}
```

---

### 5. **Espacement plus harmonieux**
Ajoute plus de cohérence dans les espaces :

```css
.text-section {
  gap: 15px; /* Augmente légèrement l'espacement */
}

.description-text {
  line-height: 1.75; /* Améliore encore la lisibilité */
}
```

---

### 6. **Utilisation de `clamp()` pour les tailles dynamiques**
Si tu veux que les titres s’adaptent mieux aux écrans, utilise `clamp()` :

```css
.main-title {
  font-size: clamp(2em, 4vw, 2.5em);
}

.section-title {
  font-size: clamp(1em, 2vw, 1.25em);
}

.description-text {
  font-size: clamp(0.95em, 1.8vw, 1.1em);
}
```

---

### 7. **Ajout d’un dégradé léger au fond de la `.wrapper`**
Cela donne un effet plus moderne :

```css
.wrapper {
  background: linear-gradient(135deg, #ffffff 0%, #f8f8f8 100%);
}
```
